test.sh

- Update Django versions, use less-than and more-than comparisons with
`pip install`.
- Do not install Django dep with test project requirements, to avoid an
error from pip with duplicated requirements/options given.
- Do not install specific django-cities-light version, handled by
test_project/test_requirements.txt.

Improve/fix test.sh

---

autocomplete_light/fields.py

RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin sub
modules of django.contrib.contenttypes.
from django.contrib.contenttypes.generic import GenericForeignKey

Fix RemovedInDjango19Warning on GenericForeignKey

---

autocomplete_light/fields.py

On PyPy, `FieldBase` crashes with the following error:
```
Traceback (most recent call last):
...
File ".../autocomplete_light/fields.py", line 33, in __init__
parents = super(FieldBase, self).__self_class__.__bases__
AttributeError: 'super' object has no attribute '__self_class__'
```
I am not sure why the code tries to access `__self_class__` like this instead of using `type(self)`: they should be equivalent in this case. The code was added in 5732ffd792a47a0c1258fd6ea47489dccb023b14, but that does not enlighten me.
Replacing the attribute access with `type(self)` lets the test suite pass successfully on PyPy 2.3.1 here.
Regarding the same line of code, I am also not sure why only `__bases__` is being inspected, instead of using a simple `instanceof` check. Is there a special reason? I …

Fix super().__self_class__ AttributeError crash on PyPy

---

autocomplete_light/static/autocomplete_light/autocomplete.js

The (shift+9) *open parentheses* `(` cannot be typed on autocomplete field. Fixed hinted by 51e20fa.

[FIX] "open parentheses" cannot be typed on Chrome/Mac

---

autocomplete_light/static/autocomplete_light/text_widget.js

Hey guys, I’ve stumbled over the case where I wanted to select a value containing an ampersand (“&”) from the autocomplete box, and the escaped value (“&amp;”) was inserted into the text input.
This PR fixes the issue.
I would appreciate if you could push a release to pip soon. Thanks!

Be friendly with special html chars in values

---

autocomplete_light/autocomplete/model.py
autocomplete_light/tests/autocomplete/test_model.py

To start with, added a failing test which asserts the AutocompleteModel.choices_for_values() does not modify the ordering of the values.
Otherwise, no implementation yet; this PR is not complete.

AutocompleteModel.choices_for_values() retains ordering of values

---

autocomplete_light/static/autocomplete_light/autocomplete.js
autocomplete_light/static/autocomplete_light/widget.js

Hello,
Thanks to your amazing package I've been able to fulfill my most advanced UX desires, you made some nice work here :)
Although I've found two small things that bothered me:
1. Prefering mousedown instead of click event allows to work on data already processed by autocomplete
2. I've used readonly inputs in my choice template, but they get picked up at initialisation, so I needed to specify the original input

Prefer mousedown and specify input

---

autocomplete_light/autocomplete/model.py
autocomplete_light/example_apps/autocomplete_test_case_app/autocomplete_light_registry.py
autocomplete_light/example_apps/autocomplete_test_case_app/forms.py
autocomplete_light/example_apps/autocomplete_test_case_app/models.py
autocomplete_light/tests/test_forms.py

Fix #412: Support models with a pk different than "id" and non-numeric.

---

autocomplete_light/static/autocomplete_light/widget.js
autocomplete_light/tests/test_widget.py

This is not my favorite fix, ideally we'd have seen this coming by
building against the master branch and were able to participate to the
elaboration of this admin widget.
So, the widget now has 2 new events it triggers:
- widgetSelectChoice,
- widgetDeselectChoice.
Also, a couple of callbacks were bound to those to support Django 1.8
change-link href management.

Fix #408: Support Django 1.8 change-link.

---

autocomplete_light/fields.py

Since validation is taken care of in the Autocomplete, there is no need to call it twice.

Fix #410: Removed double validation

---

autocomplete_light/fields.py
autocomplete_light/tests/test_fields.py

Fix for issue #429.
Like `django/forms/models.py`'s own `validate()`.

Fix #429: call Field.validate() to handle required.

---

autocomplete_light/static/autocomplete_light/autocomplete.js

In 2.2.0 series, we want most complete support of Django admin - which means
all edge cases - and it's oldschool overflow: hidden way of clearing floats.
On the other hand, we also want top-notch support for modern CSS patterns such
as the .clearfix which is the most-standard way of clearing floats IMHO and is
of course the way all modern CSS frameworks clear their floats.
By default, this traverses this.input's parents to find the nearest parent
with an 'absolute' or 'fixed' position. This prevents scrolling issues that
we'd have by boldly using <body>.

Dynamic evaluation of the autocomp box container.

---

autocomplete_light/autocomplete/model.py
autocomplete_light/example_apps/autocomplete_test_case_app/models.py
autocomplete_light/tests/autocomplete/test_model.py

The test should fail as such without the patched autocomplete/model.py::
```
========================================================= FAILURES ==========================================================
___________________________ AutocompleteModelTestCase.test_inherited_model_ambiguous_column_name ____________________________
self = <autocomplete_light.tests.autocomplete.test_model.AutocompleteModelTestCase testMethod=test_inherited_model_ambiguous_column_name>
def test_inherited_model_ambiguous_column_name(self):
class Test(autocomplete_light.AutocompleteModelBase):
choices = SubGroup.objects.all()
fixture = Test(values=[SubGroup.objects.create(name='test')])
>       len(fixture.choices_for_values())
autocomplete_light/tests/autocomplete/test_model.py:198:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

Fix #447: Wrong pk_name on subclasses.

---

autocomplete_light/autocomplete/model.py
autocomplete_light/example_apps/autocomplete_test_case_app/models.py
autocomplete_light/tests/autocomplete/test_model.py

If you added an FK with 0 as primary key, autocomplete would complain
that it was invalid because it filtered out everything Python considered
falsy after a fix to #62 was provided in #298.
After this, autocomplete validation will check directly for the empty
string '' instead of falsy values.

Foreign key with 0 as PK is valid.

---

autocomplete_light/tests/test_widget.py
tox.ini

This is required to fix the following error with `tox -e py34-django18`
(using Firefox):
> selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect.
@jpic 
Did this work for you locally?
Are you using another webdriver?

tox.ini: add DISPLAY to passenv

---

docs/source/install.rst

I think it would be better to include `{{ block.super }}` in this step of the installation process. 
I spent a bit of time on the following bug : 
I'm using django-suit and followed the installation process of django-autocomplete-light almost by the letter, except for this particular step where I copied the `{% block extrahead %} ... {% endblock %}` without `{{ block.super }}` in a file extending `admin/change_form.html` instead of `admin/base.html`.
This particular manipulation caused django-suit to never display the button "Add another Inline" when editing/adding a new object.
Adding `{{ block.super }}` fixed it and autocomplete now works flawlessly for me. Unexperienced users might have a hard time finding the source of this bug.

[fix] Docs : missing {{ block.super }} can create confusing bugs

---

docs/source/tutorial.rst

This isn't explained anywhere in the documentation, but it's the very basics of how autocomplete-light works on the surface, so I figured this is a valuable addition to the tutorial.
Maybe we should also add the full ``Person`` and ``Order`` definitions somewhere or even add the Person/Order app to the example apps in the repository.

Explain some basic concepts in tutorial

---

autocomplete_light/example_apps/basic/autocomplete_light_registry.py
autocomplete_light/tests/test_widgets.py
autocomplete_light/widgets.py

While working with autocomplete I realized that any attribute added from within __init__ will not be used by the render function. I thing this is not optimal as it is counterintuitive and results in code that is not DRY.
TIA
sandro
*:-)

Widget's render should use attrs even when created wthing __init__

---

test_project/test_requirements_without_django.txt

Ref: https://github.com/yourlabs/django-autocomplete-light/pull/501#issuecomment-145834714

tests reqs: pin pytest-django==2.8.0

---

autocomplete_light/urls.py

This is really just a test to see if CI breaks (see closed PR https://github.com/yourlabs/django-autocomplete-light/pull/501).

Fix Django 1.9 import error

---

.travis.yml

::
23:50 -!- Irssi: Join to #travis was synced in 1 secs
23:51 < is_null> hi all, is there any way i can prevent travis from testing my
branches twice when they are used for a PR ? ie.
https://github.com/yourlabs/django-autocomplete-light/pull/508#partial-pull-merging
23:52 < jhass> branches: only: - master

Prevent travis from testing branches twice.

---

autocomplete_light/tests/test_widget.py

Else, it fails as such::
self = <autocomplete_light.tests.test_dependent.DependentAutocompleteEmptyFormTestCase testMethod=test_alpes_in_france>
def set_implicit_wait(self):
>       self.selenium.implicitly_wait(WAIT_TIME)
E       AttributeError: Selenium instance has no attribute 'implicitly_wait'

Py2.7: use new style classes

---

autocomplete_light/locale/fr/LC_MESSAGES/django.po

- "votre recherche" instead of "votre rechercher".
- "dans cette autocomplétion" does not sound really goud. It would be better to say "dans ce champ de saisie automatique". However "dans ce champ" sufficient and sounds better.

Corrected french translation for "widgets.py:82"

---

test_project/test_requirements_without_django.txt

lxml is only used by autocomplete-light for tests. With version 3.4.4,
it works on PyPy:
https://travis-ci.org/yourlabs/django-autocomplete-light/jobs/87731272
But with 3.5.0 it fails:
https://travis-ci.org/yourlabs/django-autocomplete-light/jobs/91219833

Pin lxml to the last know-to-work version for pypy.

---

README

The `sed` command in the README for upgrading projects to Django 1.9 does not work on OS X and gives the following error, for example:
sed: 1: "./__init__.py": invalid command code .
This is because [OS X uses BSD `sed` which either requires `''` after the `-i` if there is no backup file extension](http://stackoverflow.com/a/16746032/996114) ~~or the use of `-e`. I used `-e` in the PR, because I think it looks cleaner than having extra quotes, but the following change also works:~~
find . -name '*py' | xargs sed -i '' 's/import autocomplete_light/from autocomplete_light import shortcuts as autocomplete_light/'
**Update:** I've actually switched the PR to use the `... sed -i '' ...` approach, because the original approach I used created unintended backup files with a suffix of `-e`.

Make sed command OS X/BSD-compatible

---

autocomplete_light/exceptions.py
autocomplete_light/fields.py
autocomplete_light/shortcuts.py
autocomplete_light/tests/test_fields.py

Django raises an exception if the queryset argument is not passed, this
patch makes it a bit easier to understand for the user.

ModelChoiceField requires the queryset argument

---

docs/source/install.rst

If you copy and paste the example code it will fail when using https for the connection.

Make the JS Urls in the Examples work with https too

---

autocomplete_light/fields.py

This PR lets you override the error message for failure to validate by passing error_messages when instantiating fields such as:
```
foo = autocomplete_light.fields.ChoiceField(autocomplete="FooAutocomplete", label="Foo", error_messages={'invalid': "Check your foo"})
```
I have not tested it, but it should also enable:
```
class BarModelForm(autocomplete_light.ModelForm):
class Meta:
model = Bar
error_messages = {
'foo': {
'invalid': "Check your foo"
}
}
```

Use error_messages on FieldBase to allow overrides

---

src/dal/static/autocomplete_light/jquery.init.js

The check if django jquery is available which resulted in a reference error if not in the django admin.
Plus added a missing statement end: `;`.

fixed loading of jquery if django version os jquery is not present

---

docs/gfk.rst

I suppose "guitars" and "trumpets" was used before using "countries" and "cities". ;)

Fixed variable names in documentation.

---

src/dal_contenttypes/fields.py
test_project/select2_generic_foreign_key/test_functional.py

However, don't let this commit fool you into thinking having duplicate
element ids in your DOM is a good thing !

Fix #628: Do not rely on ids to fix container text

---

src/dal/test/stories.py
src/dal_select2_taggit/widgets.py
test_project/select2_taggit/test_functional.py

Related commit (same for dal_select2_tagging): 47db6f0f
Thanks @dan_intro for reporting on IRC !

Bugfix: Taggit select2 widget in invalid forms

---

src/dal/test/stories.py
src/dal_select2/static/autocomplete_light/select2.js
test_project/linked_data/test_functional.py

Django forms may have a prefix, in which case all inputs of this form
will have the prefix in front of their name. It is used for example to
have 2 different forms on the same page and for formsets.

Prefix support in forward feature

---

CHANGELOG
docs/gm2m.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

docs/tutorial.rst
src/dal_select2/static/autocomplete_light/select2.js

To use:
- add the `data-html` attribute
- override `get_result_label()` to return html

Enable HTML markup in select2 item labels

---

docs/install.rst

Added note [#709](https://github.com/yourlabs/django-autocomplete-light/issues/709)

Added note for static files not checked - git submodule error

---

src/dal/static/autocomplete_light/autocomplete.init.js

django 1.9 changed  jquery.init.js file.
you can see [this](https://github.com/django/django/blob/ec4f219ecb7a5e43d0353633fac4dac42d0ee492/django/contrib/admin/static/admin/js/jquery.init.js)
the old code in release package is 
```
var django = django || {};
django.jQuery = jQuery
var yl = yl || {};
yl.jQuery = django.jQuery
// this file also prevents django.jQuery.noConflict
// there's got to be a better way ...
```
use current code will cause jQuery is undefined. it looks we have a scope error.
this PR can make our code stronger.
and I am asking why django team change this init file. if they won't plan rollback to old style. 
we have to add our jquery file. so sad.

improve compatibility for django 1.9

---

src/dal_select2/views.py

Main motivation was wanting to override this behaviour without touching
any other parts of render_to_response but I think this is also a clearer
way to organise the code.
Actually - in most cases all I really want to change is the wording of
the create text. How would you feel about a get_create_label(self,
queryset) method?
(example use case - I if someone enters a string with an @ in it I
create a new contact with an email address, otherwise I assume it's a
name - I'd like to make this behaviour explicit via the create label)

Move create_option functionality into it's own method

---

src/dal/widgets.py

Stringify values in selected_choices to match stringification of keys in filter_choices_to_render, so non-string types can be used as selected_choices (e.g. UUIDs)

Fix initial value not set when selected choices aren't strings

---

docs/gfk.rst
docs/install.rst

I've put these simple notes here, maybe we should expand those further. I hope you give further input.
Maybe in install there should be a list of DAL apps that can be installed. Then in each part of DOCS if there is a reference to that app just put a note saying it need to be added to installed apps.

Docs dal_queryset_sequence proposal.

---

docs/tutorial.rst
src/dal/widgets.py
src/dal_select2/static/autocomplete_light/select2.js
test_project/tests/test_widgets.py

Correctly show an empty option tag when a placeholder is specified, which is what the select2 library expects by design, which fixes the placeholder not used when the widget is supplied with a list of choices but no external datasource URL.

Fix placeholder not working when URL is not given to autocomplete widget

---

test_project/select2_tagging/migrations/0002_testmodel_test.py

I was trying to install the demo project today and ran into an error when running Migrate. 
Looks like test_project/select2_tagging/migrations/0002_testmodel_test.py was omitted when updating the all the Test Models in an update from 6 days ago.  I fixed it locally and it's working for me.

Updated 'testmodel' to 'tmodel' to match changes from: Fix tests (#784)

---

docs/tutorial.rst
src/dal/test/case.py
src/dal/widgets.py
test_project/select2_generic_foreign_key/test_forms.py
test_project/select2_generic_m2m/test_forms.py
test_project/select2_outside_admin/views.py
test_project/select2_tagging/test_forms.py
test_project/select2_taggit/test_forms.py
test_project/tests/test_widgets.py

Hi,
I only did a search and replace for this but I don't see what could go wrong^(tm).

Fix RemovedInDjango20Warning for 'reverse' imports

---

docs/tutorial.rst

I was trying to follow the tutorial to create an autocomplete with a static list rather than a QuerySet and was getting errors referring to Select2List. It turns out that isn't what it's called.
This commit just updates the documentation

Fix documentation error where ListSelect2 widget is named incorrectly

---

src/dal/views.py
test_project/linked_data/test_views.py
tox.ini

A simple patch to return proper information to the client side that its input data is invalid.
This is especially useful to silence errors that are not server-side when coupled with reporting tools such as [sentry](https://sentry.io/welcome/), [Airbrake](https://airbrake.io/), etc.
I did not add unittests as I got lost in the structure for functional tests as library specific tests but if you tell me where to look, I'll add them.

Return 400 on invalid input

---

src/dal_queryset_sequence/views.py
src/dal_select2_queryset_sequence/views.py
test_project/select2_generic_foreign_key/models.py
test_project/select2_generic_foreign_key/test_forms.py

The change set here uses the actual model, instead of the QuerySetSequence proxy model.
Before
After

Queryset sequence view to display actual model name

---

test_project/rename_forward/test_functional.py

I have added `test_functional` suite that reuses scenarios from `linked_data` app.
`test_forms` suite from `linked_data` seems useless for `rename_forward` app since it won't test any other functionality.
I am thinking of writing tests that checks if Select2 widget is rendered correctly, especially the forward configuration part (perhaps we can add something like that to `linked_data` app). The other good thing to test can be `LinkedDataView` to check if we're running functional tests with properly working view (the forward feature itself does not add any features to DAL views).

rename_forward tests

---

docs/tutorial.rst
src/dal_select2/static/autocomplete_light/select2.js

Now if you want custom HTML in your autocomplete widget you have to write the following code:
```python
class CountryAutocomplete(autocomplete.Select2QuerySetView):
def get_result_label(self, item):
return '<img src="flags/%s.png"> %s' % (item.name, item.name)
class PersonForm(forms.ModelForm):
class Meta:
widgets = {
'birth_country': autocomplete.ModelSelect2(
url='country-autocomplete',
attrs={'data-html': 'true'}
)
}
```
String value "true" does not look nice. Unfortunately passing `attrs={'data-html': True}` will not enable custom HTML in options since Select2 widget is rendered as follows:
```html
<select data-html="" ... > ... </select>
```
and condition in
```javascript
if (element.attr('data-html')) {
// ...
}
```
is false.
This fix allows to use boolean value in Python widget …

Allow boolean "data-html" attribute for widget on python side.

---

src/dal/static/autocomplete_light/jquery.init.js

First of all i can't see how select2 may work without a jQuery
as a global $. Said that now when i have another copy of jQuery
on top of the django one, select2 will register to $ but dal
will set yl.jQuery to the django one instead.
If we prefer using $ instead they'll both use the same jQuery
instance and magically work.
If there's not jQuery loaded as $ the code will behave as before.
This makes dal working reliably in the admin for me.

dal: prefer pristine jQuery to the django one

---

src/dal_select2/static/autocomplete_light/select2.js

`is('required')` seems to return `false` regardless of whether the field has the `required` attribute or not. This change uses a more appropriate selector to configure select2 as clearable.

Fix selector used to allow clearing non-required fields.

---

src/dal_select2/views.py

When running behind nginx, when the content-type is not specified, I get the JSON response nicely wrapped inside <body> tag, which will of course give an error on the web ui. 
I'm not sure how to test for this, except the obvious (checking for content-type in all the subclasses). I also wonder, if this won't break anything for someone else. Well. 
Let me know what do you think.

Return proper content-type for reply

---

autocomplete_light/widgets.py

Updates for version 2 for Django 1.11
The signature for build_attrs was changed for Django 1.11 widgets

Django 1.11 for V2: update build_attrs

---

docs/tutorial.rst

Hello,
I appreciate the existing warning about XSS, but since many will just copy and paste the example given here, I think it is crucial to make the example safe from XSS. Simply using `format_html` does the trick.
(Note: I have noticed that folks sometimes think `%` operator could be overloaded to do escaping automagically - so they might not even realize that what they are copy-pasting is not safe yet.)
Thanks for your consideration on this matter!
Best
Michael

Update tutorial.rst to fix XSS in the example

---

src/dal/views.py

Addresses #879.
If a user has overridden get_result_label, a newly created object still uses the six version of the text instead of using the overridden function.

Replacing call to six with call to predefined get_result_label function

---

src/dal_select2/static/autocomplete_light/select2.js

With the built in select2 functionality, the data-autocomplete-light-url can be read and modified dynamically.
For Example:
```javascript
var companySelect = $("select[name=company]");
var deliveryAddressSelect = $("select[name=delivery_address]");
companySelect.change(function (e) {
var url = "/addresses/auto-complete?company_id="
+ e.target.options[e.target.selectedIndex].value;
deliveryAddressSelect.attr("data-autocomplete-light-url", url);
});
```
If the company changes in the form, I update the query set of the addresses with the help of the query string. Like this I only get the delivery addresses possible for the given company.

Select2 url mutable

---

src/dal/static/autocomplete_light/autocomplete.init.js

Look for a csrfmiddlewaretoken input in a form on the page when the
csrftoken cookie is not present. This is commonly caused by
a CSRF_COOKIE_HTTPONLY = True setting for the app.
Closes: #772

Fetch csrftoken from DOM when not found via cookie

---

docs/install.rst

Django 2.0 doesn't support python 2 any more, thus we need to be sure to use python 3 in the virtual env.

Documentation: Adjusting virtualenv to use Python 3

---

docs/tutorial.rst
src/dal/forward.py
src/dal/static/autocomplete_light/forward.js
src/dal_select2/static/autocomplete_light/select2.js
src/dal_select2/widgets.py
test_project/forward_different_fields/forms.py
test_project/forward_different_fields/static/js_handlers.js
test_project/forward_different_fields/urls.py

This work is based on #843 and adds two more forward features.
Currently there are no tests and docs and the purpose of this PR currently is to illustrate my comment in #894 .
The idea is following:
On server side user defines `Js("someCallback")` as a forwarded value. After that somewhere is JS he should register this callback to DAL:
```js
yl.registerForwardHandler("reverse_name", function(elem, prefix) {
// Do stuff and return forwarded value
return 42;
});
```
One thing to be considered is to expose some DAL machinery used for searching fields and extracting values as DAL JS API (like `getFieldRelativeTo` and `getValueFromField`).
Another feature implemented here is forwarding values from DAL widget itself (`Self()`).

More forward features

---

src/dal/static/autocomplete_light/autocomplete.init.js

This PR proposes to use the same selector in `DOMNodeInserted` callback as we use in `document.ready` callback.
The old version works well in most cases: we avoid select2 init on template form (that matches `[id*="__prefix__"]`) only in `document.ready`. The most calls to `DOMNodeInserted` are performed when user clicks "Add": the template form is cloned and inserted as new node, so we don't have to avoid `[id*="__prefix__"]` here. 
However, in some rare cases the template form itself is not present on page load and added to the page later (by AJAX for example). In that case Select2 is initialized twice: first for template form and then again when it is copied. This patch fixes this case.
It does not break anything on latest Django in admin, however I am not sure about older Django …

Use proper selector in DOMElementInserted

---

src/dal_select2/views.py

**Warning** this is untested. I have splinter errors when running tox.
http.HttpResponse with manual json.dumps call is, well, kind of acceptable. Unless you forget to set content_type to „application/json”. But then, everything still is fine, tests pass and stuff. But then, after some time, you run the code in the production, on, say, nginx+uwsgi. This combo will attach HTML tags to your json responses, head, body, the html tag itself, thus rendering json responses as unreadable to the client.
TL;DR: Use http.JsonResponse when the response is JSON

Use http.JsonResponse when the response is JSON

---

src/dal/static/autocomplete_light/autocomplete.init.js
src/dal_select2/static/autocomplete_light/select2.js

There is a bug in „Create” option behavior, when some javascript files are included multiple times.
The premise of this bug is: I have no control over what my django.admin includes in the HTML source. I do have a global search form, based on autocomplete, so I need to include dal JavaScript on every single page. And, occasionally, I do have a form with autocomplete. Django admin adds form.media, so I may get dal's JavaScript included many times.
If I include autocomplete.init.js and/or select2.js more than once, I do get a strange, erroneous behaviour but when? Only when I use that small, very useful "Create '%s'" option.
The item created gets submitted more than once. It gets submitted so many times as the times the autocomplete.init.js and select2.js is included. So, usually the first …

Fix #981, „create” option wrong behavior

---

src/dal/views.py

Setting the class attribute `paginate_by = None` on a `Select2QuerySetView` subclass causes `BaseQuerySetView.has_more()` to raise an exception because `context['page_obj']` is `None`. 
This PR fixes that problem by having `has_more()` check if `context['page_obj']` is `None` before calling `has_next()` on it.

Fixed exception raised from Select2QuerySetView when paginate_by is set to None

---

docs/tutorial.rst

In the example given, the forward argument in line 590: ```forward=(forward.Self())``` isn't a tuple. So I've updated the example to correct the error and also added a reminder that the forward argument expects a tuple.

Forward argument should always be a tuple

---

src/dal_select2/widgets.py

Django2 introduced the SELECT2_TRANSLATIONS dictionary, and this
was imported into the dal_select2.widgets module, causing an ImportError
when run against any version of Django < 2.
Fixes #1029

Fix ImportError with SELECT2_TRANSLATIONS in Django 1.x

---

src/dal/widgets.py

The renderer parameter is mandatory in django 2.1, and it solves the issue #1026.

Added missing renderer parameter to render method for django 2.1

---

.travis.yml
AUTHORS
tox.ini

Django 2.1 has been released last week, so adding it to the build matrix.
This should help reproduce bugs like #1026 which is a problem only on Django 2.1+

Add Django 2.1 to the build matrix

---

src/dal_select2/static/autocomplete_light/select2.js

This PR sets `containerCssClass: ':all:'` option when initializing select2. In the generated element, this makes select2 use the same CSS classes as were set on original select element.
This fixes some select2 display bugs that are encountered with Bootstrap 4. Bootstrap requires the form elements to have `form-control` class, which is lost on a generated element without this fix. See example [here](https://github.com/select2/select2-bootstrap-theme/pull/72#issuecomment-381151068).

Set select2 container CSS class to :all:

---

src/dal/static/admin/js/jquery.init.js
src/dal/static/autocomplete_light/jquery.init.js
src/dal_select2/widgets.py

The comments in the diff go into detail about what this is doing, but the gist of this PR is that DAL's method of including Django's copy of jQuery was interfering with other javascript that was expecting a newer version of jQuery to be installed. I removed the override of `admin/js/jquery.init.js`, since DAL's version was doing it wrong, and changed `autocomplete_list/js/jquery.init.js` to do it right. The widget code now adds the jQuery from Django and then immediately removes it from the global namespace, restoring whatever version of jQuery was installed above the DAL widget code.
I originally discovered this problem when using a DAL widget on a Wagtail Page form that also had a DateTimeField. `jQuery.dateTimePicker()` was becoming undefined as soon as I added a DAL widget, and that …

Fixed a jQuery conflict bug in the widget code.

---

docs/tutorial.rst

Hi,
The class has an uppercase `S`: https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/forward.py#L99

Doc: Fix forward JavaScript case

---

src/dal_queryset_sequence/fields.py
src/dal_queryset_sequence/views.py
test_project/select2_generic_foreign_key/test_forms.py

- fixes the breaking change of django-querysetsequence v0.9 keeping backward compatibility #1050.
- comments out a test case that needs some attention to be fixed.

Remove phantomjs

---

src/dal/static/autocomplete_light/forward.js

Maybe its possible to fix it within the Django code, but the fix works and there's no need not to serialize disabled fields, since we won't insert these into a Database / update a entry

Fix: Forward ignores read_only fields

---

src/dal_queryset_sequence/fields.py
src/dal_queryset_sequence/views.py

Switches from using an unsupported private API (which changed and broke
from django-querysetseqence>0.7) to a newly added public api method
(`get_querysets`) which achieves the same thing.
Depends on https://github.com/percipient/django-querysetsequence/pull/53
Supersedes #1056
Fixes #1050

[WIP] Switch to public api for retriving QSS querysets

---

src/dal_select2/widgets.py

Hi,
there's a bug on rendering widget data of integrated `django-taggit` module.
`TagSelect2` class expects nested iterables but gets only flat list.
Thanks for your comments!

Fix not iterable tag value

---

.travis.yml
tox.ini

- fixes xvfb errors, cause by change in travisci environment
- workaorund for flake-docstrings error in testqa
- workaorund/fix line length erros from testqa
Since the lines causing the flake8 errors had already been merged and released I did the easiest thing and made 88 the new limit (borrowing from black's defaults), but that is debatable :)

Travisci fixes

---

.gitmodules
src/dal_queryset_sequence/fields.py
src/dal_select2/widgets.py
src/dal_select2_queryset_sequence/fields.py
test_project/custom_select2/widgets.py
test_project/select2_nestedadmin/test_functional.py
test_project/select2_taggit/test_forms.py

This patch adds kind of support for python2:
- select2 is back as a submodule, django 2 is not required anymore, and we can better follow releases from select2
- language code detection does not benefit from lru_cache in python2, but PR welcome
- a few tests still don't pass on python2, because dicts are not ordered
Besides those minor drawbacks it looks like this would work on python / dj111.
Would anybody like to test prior to merge and release ?
Remember to use git clone --recursive

Python 2 support (mostly)

---

.travis.yml
conftest.py
src/dal/test/case.py
tox.ini

This gets the liveserver/splinter/selenium based tests working again on TravisCI.
Did add a python 3.6 test run, just to show it can run without failures.
The 3.5 run shows 1 error, looks like dictionary/hash ordering problem in the test itself, so unrelated to this pull requests change (better fixed separately).

Replace phantomjs with firefox

---

src/dal_select2/static/autocomplete_light/select2.css

Since the Django generated select box is hidden with select2, the red border style does not appear when there is an error. This fix adds that style the select2 box.

Highlight select field with error to match Django style

---

src/dal/static/autocomplete_light/autocomplete.init.js

This minor JS change enables DAL to work with the `jquery.formset.js` plugin that is commonly used. This PR reverses a change made a few versions ago adding more specificity to the `initialize`.

Initialize all items on DOMNodeInserted and don't exclude prefix

---

src/dal/forms.py

There is a small typo in src/dal/forms.py.
Should read `writing` rather than `writting`.

docs: Fix simple typo, writting -> writing

---

src/dal/static/autocomplete_light/autocomplete.init.js

Hello, I noticed issues (#851 and #910 ) were opened related to `autocomplete.init.js` using `$(document).bind('DOMNodeInserted')` quite a while ago. However, it looks like the code related to these issues is [still there](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/static/autocomplete_light/autocomplete.init.js#L93). I decided to take a crack at a patch to address those issues with this proposed update to the `autocomplete.init` script. 
This uses a `MutationObserver` to watch for new widgets to initialize and falls back to `DOMNodeInserted` if `MutationObserver` is not available.

Update autocomplete init

---

src/dal_queryset_sequence/widgets.py

If a model is using a UUIDField for its primary key, the QuerySetSequenceSelectMixin breaks on the following line:
`ctype_pk, model_pk = choice.split('-')` as we're expecting a tuple but UUID PK's have additional -'s. This is fixed by forcing the split to only split once. You can see this pattern already in another part of the codebase, i.e. dal_queryset_sequence/fields.py, line 50: 
`return value.split('-', 1) `

Bug fix: QuerySetSequenceSelectMixin breaks when model uses UUID for PK

---

src/dal_select2/static/autocomplete_light/select2.js

select2 erroneously calculates the width of the elements. It has been a knows issues for a while: https://github.com/select2/select2/issues/208 It's not resolved, but there is a workaround:
```js
$(element).select2({
...
width: null
...
});
```
If there is a need to readjust the width It should be done vis CSS or dynamically after completion of rendering.
This is how the UI looks with ModelSelect2 before:
After:

remove calculated widths

---

docs/tutorial.rst

- Minor doc update: https://docs.djangoproject.com/en/dev/releases/1.10/#using-user-is-authenticated-and-user-is-anonymous-as-methods
- `is_authenticated` does work as a property and a method up until Django 2.0

Django 1.10+, is_authenticated is a property

---

src/dal/views.py

Implements search_fields and split_words as they were in v2 and discussed in #783 
Also implements simple template support, similar to v2.
Having the filtering logic be in its own method, `get_search_results` is important to allow for subclasses to override the filtering logic for things such as forwards, without losing the ability to pick up on `model` or `queryset` attribute from `BaseListView`'s `get_queryset` method.

Implement search_fields, split_words and template properties

---

src/dal_select2/static/autocomplete_light/select2.js

Fix for displaying [object Object] when data-html is true and object creation allowed, see ticket #1171
Untested, going purely from ticket comments.

Potential fix for #1171

---

src/dal_select2/widgets.py

I'm working on a project that is still on python <3.3 and I'm seeing a lot of the "Python2: no cache on get_i18n_name until contribution" warnings. It seems like the best way to get rid of these warnings is to use `filterwarnings`. However, it would be nice to still be able to use the `get_i18n_name` caching.
This PR allows python <3.3 users to get rid of the warning and enable the `get_i18n_name` caching by using `lru_cache` from `backports.functools_lru_cache` if it's available.

use backports.functools_lru_cache for lru_cache if available

---

docs/tutorial.rst

link is stale and resolves one level higher in the select2 docs than is needed.

Update data-* docs link

---

src/dal_legacy_static/static/admin/css/autocomplete.css
src/dal_legacy_static/static/admin/js/autocomplete.js

Added missing `autocomplete` files (copied from Django version 2):
- `/css/autocompolete.css`
- `/js/autocomplete.js`
NOTE: In the chrome console I could see an error about `css` file missing only but apparently I could not find `js` file in static also. Adding JS file just in case...
Fixes #1188 
Additions for #1085

Add missing `autocomplete` JS and CSS files to dal_legacy_static

---

src/dal/autocomplete.py
src/dal_select2/views.py

Hello!
Tried to use this new base view today (PR #1186) but ran into some issues, namely it would crash at [line 113](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/views.py#L113):
```python
'title': result.descricao  # raises AttributeError
```
I suspect that it could be a project-specific property used by the author of original PR, so I though I'd replace it with the methods used throughout the repo to resolve id/text of the resulting items.
Sadly I wasn't able to add some test coverage; in fact I wasn't able to run existing tests either - would love if somebody could guide me as there seem to be quite a lot of setup. That said, I've tested proposed implementation manually and can confirm it works just fine.

fix Select2GroupQuerySetView

---

src/dal/static/autocomplete_light/autocomplete_light.js

Fixes issue https://github.com/yourlabs/django-autocomplete-light/issues/1239

#1239 fixes Django 3.2+ Ajax parameter requirements

---

src/dal_select2/__init__.py

RemovedInDjango41Warning: 'dal_select2' defines default_app_config = 'dal_select2.apps.DefaultApp'. Django now detects this configuration automatically. You can remove default_app_config.

Fix RemovedInDjango41Warning

---

docs/tutorial.rst

Overriding the `get_result_label` method requires the second param to be called "result" - not "item".
Otherwise, Pylint throws an arguments-differ error (W0221)

📄 fix(docs): rename `get_result_label` parameter

---

src/dal_select2/views.py

Sometimes it desired to have a possibility to create case-sensitive options Select2QuerySetView.
For example image a situation when you are trying to use Select2QuerySetView to choose a unit (e.g. file size).
These units are case-sensitive `MB` vs `Mb`. In current implementation it is not possible to create both `Mb` and `MB` in the search field.
This patch makes it easier to achieve such functionality by overriding Select2QuerySetView.
```python
class CustomSelect2QuerySetView(Select2QuerySetView):
case_sensitive_create = True
```

Add a possibility to have case-sensitive creates using Select2QuerySetView

---

src/dal/static/autocomplete_light/autocomplete_light.js

When dal is initialized multiple times, yl.functions stays set to {} and the select2 function is no longer present. This causes any future dal fields not to render and instead appear as normal HTML select fields. 
This error came up when I tried using HTMX in conjunction with dal. HTMX reloads the form on the fly using ajax calls. When it pulled the new form in and tried to render it, the script tags for dal were loaded again. Thus producing this error.

Fixes an issue when dal is loaded twice

---

src/dal_legacy_static/static/admin/css/vendor/select2/select2.css

In the dark mode the text color of the selected field is not visible. The dropdown list's text color is also not visible (images attached).
The issue is also mention in #1245 .

Compatibility with dark mode.

---

test_project/templates/base.html
test_project/urls.py
test_project/views.py

Something sorely lacking from the test_project seems to be a really stripped down, isolated test of the single and multiselect widgets. Very useful and important, I believe, for seeing the very bare minimum configuration for a working widget without a lot of very distracting dressing in templates and views. These a totally drab new pages to demonstrate the stripped down bare minimalist widgets in action.
That said, something is wrong, and this first cut serves as little more than a minimal, stripped down demonstration of the focus bug being discussed (https://github.com/yourlabs/django-autocomplete-light/issues/1283). It is either a DAL bug or an incorrect use of DAL, but this tiny little view will help anyone assessing it to offer commentary on what has gone wrong. There's almost nothing …

Two isolated unadorned simple test cases added

---

docs/gfk.rst

This mirrors the reminder elsewhere in the documentation "# don't forget to pip install djhacker".  Several issues have been started in the past due to the error that's caused by forgetting (or not understanding) that this isn't installed by default.  e.g. #971.  Just happened to me now.

Add reminder to install django-querysetsequence

---

src/dal/forms.py
src/dal/test/stories.py
src/dal_queryset_sequence/fields.py
src/dal_select2_queryset_sequence/views.py

There are small typos in:
- src/dal/forms.py
- src/dal/test/stories.py
- src/dal_queryset_sequence/fields.py
- src/dal_select2_queryset_sequence/views.py
Fixes:
- Should read `necessarily` rather than `necessarely`.
- Should read `submitted` rather than `submited`.
- Should read `imprecise` rather than `unprecise`.
- Should read `different` rather than `diffrent`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

.travis.yml
tox.ini

This PR updates the tox and travis config files to drop old versions of Django and Python, and test Django 4.1.
I tried running the tests locally. The unit tests pass, but those using splinter fail. It seems pytest-splinter is incompatible with some changes to splinter. I tried rolling back splinter as far as version 0.14, but that only got me different errors. The errors with the latest splinter are all:
```
@pytest.fixture(scope="session")
def browser_patches():
"""Browser monkey patches."""
patch_webdriver()
>       patch_webdriverelement()
../.tox/py310-dj41/lib/python3.10/site-packages/pytest_splinter/plugin.py:278:
_ _ _ 
def patch_webdriverelement():  # pragma: no cover
"""Patch the WebDriverElement to allow firefox to use mouse_over."""
def mouse_over(self):
"""Perform a mouse …
```

Test Django 4.1

---

docs/tutorial.rst
src/dal/views.py
src/dal_select2/static/autocomplete_light/select2.js
test_project/select2_one_to_one/models.py
test_project/select2_one_to_one/urls.py

Add the option of validating the data when creating a new option.
Result in the example if we try to create a new option with the added validate_slug 
```
@python_2_unicode_compatible
class TModel(models.Model):
name = models.CharField(
max_length=200,
validators = [validate_slug]
)
```

Add the option to validate the field when creating a new choice

---

src/dal/static/autocomplete_light/autocomplete_light.js

Fixing an issue where dragging an inline admin section would initialize the autocomplete fields during the dragging phase and when dragging stopped the autocomplete field would be reset and not get initialized again since the internal initialized list would already contain that element.
To prevent this, added a check to the DOM listener logic to verify that the container element being added isn't the one used to represent the element while it is being dragged.
https://user-images.githubusercontent.com/6753326/191374994-cdae0bb1-d244-447b-9417-2a062821e443.mov
https://user-images.githubusercontent.com/6753326/191375318-99a9cb2a-46e6-4fa3-a77e-b30f0ba68411.mov

Fix django-nested-admin dragging fields

---

src/dal_select2/static/autocomplete_light/select2.css

This fixes #1245 where the select2 fields don't honor the Django dark mode theme.
The fix requires using the CSS variables defined by the Django admin. These variables get used for both dark mode and light mode. For older Django versions < 3.2 before these variables were added, a fallback value is provided that matches the default styling that select2 was using.
Below you can see the comparison between the different fields and their states before and after these changes are applied.
<details><summary>Dark Mode Comparison</summary>
<p>
<details><summary>List comparison</summary>
<p>
</p>
</details>
<details><summary>Table comparison</summary>
<p>
| Field Type | Field State | Before | After |
| --- | --- | --- | --- |
| Multiple Choice | Empty/Inactive | <img width="1159" alt="image" …

Adding dark mode support

---

src/dal/views.py

This resolves https://github.com/yourlabs/django-autocomplete-light/issues/1300.
Currently the pk of new object is returned when a new option is created, regardless if you override get_result_value(). 
Use get_result_value() when returning new option from post()

Use get_result_value when returning created object

---

src/dal/widgets.py

Users may craft an invalid choice, for example, entering a string where an integer based ID is expected, and this would result in a ValueError when trying to render the field in a django template.
This PR catches cases where an the choices are invalid and silently continues.  You could also set the queryset of choices to be empty, but this was a less disruptive (though perhaps harder to debug) option.
This fixes errors like those below, if a user manually sets a value like `abc` where an integer-based ID is expected:
```
File "../dal/widgets.py", line 187, in filter_choices_to_render
qs = self.choices.queryset.filter(pk__in=[c for c in selected_choices if c])
File "../django/db/models/query.py", line 941, in filter
return self._filter_or_exclude(False, args, kwargs)
File …
```

catch ValueError if selected_choices are invalid

---

pytest.ini

pytest warns about this key:
```
../.tox/py310-dj42/lib/python3.10/site-packages/_pytest/config/__init__.py:1302
/Users/chainz/Documents/Projects/django-autocomplete-light/.tox/py310-dj42/lib/python3.10/site-packages/_pytest/config/__init__.py:1302: PytestConfigWarning: Unknown config option: plugins
self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
```
I thought it might be an old thing but I also can't find mention in the pytest changelog: https://docs.pytest.org/en/stable/changelog.html
Anyway, the tests work without it set, still loading the splinter plugin.

Remove 'plugins' from pytest.ini

---

docs/taggit.rst

Hi! I ran into this issue and figured out a fix. Maybe this is not the correct change to make or document -- if it isn't, please let me know how to address this in my app + I'd be happy to update the PR to address the underlying code instead if that's the issue.
---
For `taggit` the create option is broken, and it is unnecessary.
One of the drop down options includes the new tag. So if you've typed `funny` and `funny` does not exist you'll have:
```
funny
Create 'funny'
```
Picking `funny` works as intended -- it creates a new tag properly.
Picking `Create 'funny'` creates two tags and labels them wonkily.
This change removes the create option entirely from the docs so this works out of the box for end-users.

Update taggit.rst docs.

---

src/dal/static/autocomplete_light/autocomplete_light.js
src/dal_legacy_static/static/admin/js/autocomplete.js

Event format has been changed for Django 4.2, and old variant isn't working.
https://github.com/django/django/commit/eabc22f919e6c1774842e628400b87ac56c47bce
This PR fixes it, but we need to decide how to handle the old django versions.
Cleaner variant would be to support only latest django version, and those with old version should use old library versions.
If we want to support all django versions, i need to modify this, to check if `$newFormset` is defined or not, and then use two different call variants.
What do you think?

fix: Fix event format for Django 4.2

---

.travis.yml
setup.py
test_project/requirements.txt
tox.ini

Add official support for this [new Django version](https://docs.djangoproject.com/en/5.0/releases/5.0/), currently in beta. Based on the changes needed back in #1324.
Still working on getting tests running cleanly locally, looks like there are new warnings to fix.

Test on Django 5.0

---

docs/tutorial.rst

Missing these spaces caused the JavaScript code blocks in the tutorial to not display properly, leading to confusion.

Fix the issue of invisible JavaScript code blocks in tutorial.rst.

---

test_project/select2_generic_foreign_key/urls.py
test_project/select2_many_to_many/urls.py

Fix some warnings in the vein of #1326:
```
test_project/select2_generic_foreign_key/test_forms.py::GenericFormTest::test_initial
/.../test_project/select2_generic_foreign_key/urls.py:13: SyntaxWarning: invalid escape sequence '\d'
'test/(?P<pk>\d+)/$',
test_project/select2_generic_foreign_key/test_forms.py::GenericFormTest::test_initial
/.../test_project/select2_many_to_many/urls.py:20: SyntaxWarning: invalid escape sequence '\d'
'test/(?P<pk>\d+)/$',
```
The warning is `SyntaxWarning` from Python 3.12 onwards, with the aim to remove support soon.

Fix more string escape warnings

---

src/dal/views.py

On [Creation of new choices in the autocomplete form](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#creation-of-new-choices-in-the-autocomplete-form), when we use `validate_create=True` and the validation failed we have `TypeError: Object of type ValidationError is not JSON serializable`.
Corrections made :
- fix the TypeError
- return of the error of the concerned field to the view
Versions used:
- django==5.0.7
- django-autocomplete-light==3.11.0

Fix - Object of type ValidationError is not JSON serializable

---

src/dal/widgets.py
src/dal_select2/static/autocomplete_light/select2.js

Actually, for field forwarding, there is a mismatch between the div `id` given at python side and the `id` at javascript side. At python side the widget `id` is not read at the right place.
In the PR there is a very quick fix for that.
There is also a XSS exploit possible in select2.js when displaying selected item : it requires to be escaped.

WidgetMixin : take the right id in the right place for field forwarding + XSS exploit fix
