autocomplete_light/tests/autocomplete/case.py
autocomplete_light/tests/autocomplete/generic.py
autocomplete_light/tests/forms.py
autocomplete_light/tests/registry.py
autocomplete_light/tests/templatetags.py
autocomplete_light/tests/views.py

This should result in less broken tests (https://github.com/pytest-dev/pytest-django/pull/197#issuecomment-70806617), and will make it easier to use pytest.

Use Django's TestCase

---

.travis.yml

Use travis' new [caching mechanism](http://docs.travis-ci.com/user/caching/) to create and use wheels during install.

Travis: cache wheels

---

.travis.yml
autocomplete_light/tests/test_widget.py

Cherry-picked from 2160ae3.
Conflicts:
.travis.yml
autocomplete_light/tests/widget.py

Try PhantomJS on travis (again)

---

autocomplete_light/fields.py
autocomplete_light/tests/test_fields.py

Potential fix for #379.  Maybe the regression tests are overkill...

fix and regression tests for #379

---

.travis.yml
autocomplete_light/autocomplete/model.py
pytest.ini
test_project/test_project/settings_mysql.py
tox.ini

Sbaum fix 20150519

---

docs/source/index.rst

Improving titles and toc indexes for issue #476

#476 - Documentation is a mess 

---

.travis.yml
autocomplete_light/tests/test_exceptions.py
tox.ini

Before, we were actually testing against django 1.10 in djangomaster job.

Test against django 1.9 explicitely

---

autocomplete_light/locale/pl/LC_MESSAGES/django.po

Update polish translation

---

autocomplete_light/example_apps/create_choice_on_the_fly/admin.py
autocomplete_light/example_apps/create_choice_on_the_fly/autocomplete_light_registry.py
autocomplete_light/example_apps/create_choice_on_the_fly/forms.py
autocomplete_light/example_apps/create_choice_on_the_fly/models.py
autocomplete_light/example_apps/create_choice_on_the_fly/static/create_choice_on_the_fly/fly_widget.js
docs/source/script.rst

Ref: https://github.com/yourlabs/django-autocomplete-light/issues/290

Improvements to on-the-fly example widget

---

autocomplete_light/example_apps/create_choice_on_the_fly/autocomplete_light_registry.py

Followup to 5c45fbd31c61dc72ce1e620c2840f06334f1cc3c.
Ref: https://github.com/yourlabs/django-autocomplete-light/commit/5c45fbd31c61dc72ce1e620c2840f06334f1cc3c#commitcomment-14603461

OnTheFlyAutocomplete: improve check for existing choice

---

src/dal/static/autocomplete_light/jquery.init.js

The check if jquery is available resulted in a reference error.

fixed loading of jquery if jquery is not present

---

docs/taggit.rst

The taggit example as provided by the tutorial did not work. This pull request will restore basic functionality.
Cheers,
Alex

fix taggit example in tutorial

---

docs/tutorial.rst

it should return queryset not self.q

fix tutorial get_queryset implementation

---

docs/tutorial.rst

Add user property for request. Now the tutorial is clear.

Fix tutorial.rst

---

docs/tutorial.rst

Fixed documentation

---

src/dal_select2/__init__.py
src/dal_select2/apps.py
src/dal_select2/checks.py

Blow up at the face of users trying to start dal_select2 without select2 :D
ie. #635
Should help a lot ^^

Check if submodules are cloned

---

src/dal_select2/static/autocomplete_light/select2.js

This should perhaps be fixed upstream.

Fix #628: Trigger change on the select on subtree modification

---

src/dal/views.py
src/dal_select2/static/autocomplete_light/select2.js

extend 'forward' attribute (linked data feature) to creating objects as well

fix for #677

---

src/dal_select2/views.py

Hi,
Thanks for your work on dal.
This little change allow to translate the message displayed by dal to create new item.

allow create message translation/customization

---

setup.py

Ref: https://github.com/nvie/pip-tools/pull/354

setup.py: use lowercase and no space with `extras_require`

---

test_project/select2_generic_foreign_key/models.py

Resolve SystemCheckError fields.E304

---

AUTHORS
src/dal/static/autocomplete_light/jquery.init.js

https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#internationalization-in-javascript-code
DAL breaks with i18n

Fixed integration with django js i18n

---

docs/tutorial.rst
src/dal_select2/views.py
test_project/select2_list/test_views.py

-Made select2ListView return a case insensitive match by default
to match the select2QueryView
-Added a kwarg to toggle case sensitivity in select2ListView get()

Made Select2ListView return case insensitive results by default

---

src/dal/widgets.py

Prevent rendering of empty option on multi select

---

src/dal/views.py

~~I just copied all of the tests from `select2_foreign_key` into `select2_foreign_key_uuid`~~
Closes #781.

Support serializing UUIDs and add tests for models with UUIDs as PKs

---

src/dal_select2/static/autocomplete_light/select2.js
test_project/rename_forward/forms.py
test_project/rename_forward/urls.py

+ also add simple test that only outputs the checkbox state to console

Add checkbox handling in forwards

---

autocomplete_light/autocomplete/base.py
autocomplete_light/forms.py

For those who still uses v2 this patch fixes compatibility with django 1.11

Fix v2 compatibility with django 1.11

---

autocomplete_light/autocomplete/base.py

Fix misprint in previous pull request #889

Fix v2 compatibility misspelling

---

src/dal/forms.py

I'm not 100% certain about this, so this PR is also a request for clarification.

Fix a mistake in the documentation

---

docs/tutorial.rst

https://github.com/yourlabs/django-autocomplete-light/issues/918#issuecomment-333366515

Improve create-new-object docs with example

---

docs/install.rst

While in here, reorganize a bit and improve wording.
Closes #928.

Fix #928: Add note about slim jqueries

---

src/dal_select2_queryset_sequence/views.py
tox.ini

Fix #930: queryset ordering

---

docs/tutorial.rst

Apologies, this is just cleaning up a comment that was my own mess from my previous MR: https://github.com/yourlabs/django-autocomplete-light/pull/937

Tiny cleanup in tutorial.rst

---

README

Remove broken link to live demo.

---

src/dal/forms.py
src/dal/forward.py
src/dal_queryset_sequence/fields.py
src/dal_select2/apps.py
src/dal_select2/views.py
src/dal_select2/widgets.py
src/dal_select2_queryset_sequence/fields.py
src/dal_select2_queryset_sequence/views.py
test_project/forward_different_fields/urls.py
test_project/select2_generic_foreign_key/forms.py
test_project/select2_generic_foreign_key/test_forms.py
test_project/select2_generic_foreign_key/urls.py
test_project/tests/test_widgets.py
test_project/urls.py
tox.ini

The `flake8` errors has been fixed. The build still will not pass on master branch as the build fails while deploying the master branch if it does not fail on `flake8` tests.

Fix all flake8 issues in the code

---

src/dal_select2/views.py

Hello,
the commits fix a missing translation in Select2ListView.
Regards :-)

Translate the create option text in Select2ListView

---

src/dal_queryset_sequence/widgets.py

Use `label_from_instance` in QuerySetSequenceSelectMixin

---

src/dal_select2/widgets.py
test_project/select2_generic_foreign_key/test_forms.py
test_project/tests/test_widgets.py

Ensure language support

---

setup.py
src/dal/static/autocomplete_light/forward.js
src/dal/widgets.py
test_project/requirements.txt
test_project/select2_generic_foreign_key/test_forms.py

https://github.com/yourlabs/django-autocomplete-light/issues/1099

django-nested-admin NestedStackedInline/NestedTabularInline adding new row does not forward fields

---

setup.py
src/dal/test/case.py
src/dal/test/stories.py
src/dal/views.py
src/dal/widgets.py
src/dal_contenttypes/fields.py
src/dal_select2/views.py
src/dal_select2/widgets.py
src/dal_select2_queryset_sequence/views.py
src/dal_select2_taggit/widgets.py
test_project/custom_select2/models.py
test_project/forward_different_fields/models.py
test_project/linked_data/models.py
test_project/rename_forward/models.py
test_project/secure_data/models.py
test_project/select2_generic_foreign_key/models.py
test_project/select2_generic_foreign_key/test_forms.py
test_project/select2_generic_m2m/models.py
test_project/select2_generic_m2m/test_forms.py
test_project/select2_gm2m/models.py
test_project/select2_list/models.py
test_project/select2_list/test_functional.py
test_project/select2_many_to_many/models.py
test_project/select2_nestedadmin/models.py
test_project/select2_one_to_one/models.py
test_project/select2_tagging/models.py
test_project/select2_tagging/test_forms.py
test_project/select2_taggit/models.py
test_project/select2_taggit/test_forms.py
test_project/tests/test_widgets.py

Fix Compatibility issue with Django 3.0 due to django.utils.six

---

src/dal_select2/widgets.py

Do not load jquery in Select2WidgetMixin

---

.travis.yml
docs/api.rst
docs/conf.py
docs/gfk.rst
docs/tagging.rst
docs/tutorial.rst
src/dal/forms.py
src/dal/widgets.py
src/dal_queryset_sequence/views.py
src/dal_select2_queryset_sequence/views.py
src/dal_select2_queryset_sequence/widgets.py
test_project/requirements.txt
tox.ini

This fixes the current warnings and adds a CI job to prevent such
warnings to occur again.
Also disables the travis job because it's not working anymore, despite
that it's still working great on my laptop which is enough for me, given
a pretty low contribution activity on this repo.

Fix #1129: documentation

---

README
setup.py
src/dal/forward.py
src/dal/static/autocomplete_light/autocomplete.init.js
src/dal/widgets.py

Fixes several minor spelling and grammatical mistakes in documentation and docstrings.

Fix spelling and grammar in documentation

---

src/dal/views.py

Return selected result label for created option (#879)

---

docs/tutorial.rst
src/dal/autocomplete.py
src/dal_select2/fields.py
src/dal_select2/views.py
test_project/select2_list/forms.py
test_project/select2_list/test_fields.py
test_project/select2_list/test_views.py
test_project/select2_list/urls.py
test_project/select2_list/views.py

- Updated Select2ListView, Select2GroupListView, & Select2ListChoiceField to account for the extra functionality
- Added tests
- Updated docs to reflect
Have successfully run the tests, and implemented multiple versions of the resulting view & form variations in my own project.

Added ability to specify value on list and group-list selections

---

docs/install.rst

First I read that jQuery 3 is not supported.

More explicit: "slim" version

---

src/dal_select2/static/autocomplete_light/select2.js

Attempt to fix #1219

---

src/dal/views.py

I thought there is a redundancy in a comment so I removed it.

Fix comment of ViewMixin class

---

tox.ini

https://github.com/django/django/pull/14048

Update django master to django main

---

src/dal/views.py
src/dal_select2/views.py

Fix missing functions in Django 4.0
Fix for #1260

Add support for Django 4.0

---

src/dal/views.py
src/dal_queryset_sequence/views.py
test_project/select2_generic_foreign_key/test_views.py

Depends on: 
- https://github.com/clokep/django-querysetsequence/pull/76 (likely to merge)
- https://github.com/clokep/django-querysetsequence/pull/77 (unsure)

Fix search_fields support on QuerySetSequence

---

src/dal_queryset_sequence/fields.py
src/dal_queryset_sequence/widgets.py
src/dal_select2_queryset_sequence/fields.py
test_project/custom_select2/urls.py
test_project/forward_different_fields/urls.py
test_project/linked_data/urls.py
test_project/rename_forward/urls.py
test_project/requirements.txt
test_project/secure_data/urls.py
test_project/select2_foreign_key/urls.py
test_project/select2_generic_foreign_key/urls.py
test_project/select2_generic_m2m/urls.py
test_project/select2_gm2m/urls.py
test_project/select2_list/urls.py
test_project/select2_many_to_many/urls.py
test_project/select2_nestedadmin/urls.py
test_project/select2_one_to_one/urls.py
test_project/select2_outside_admin/urls.py
test_project/select2_tagging/urls.py
test_project/select2_taggit/urls.py
test_project/tests/test_widgets.py
test_project/urls.py
tox.ini

Fix Django 4 support
Do not deploy in 3.9 as this will probably break some Django 2.x support and even more whatever still works on Django 1.x

Django 4.0 test

---

.travis.yml
setup.py
tox.ini

Extend Python support, add support for Django 5.1
